### ISSUE TITLE
NewResourceName: AdcsAiaExtension 

### ISSUE THREAD

**Issue by alsitton** [dsccommunity/ActiveDirectoryCSDsc#78]
### Description
My team has been working on adding a new DSC resource module to the ActiveDirectoryCSDsc module. This new resource module allows us to add/remove AIA URI extensions on a Certificate Authority and to restart the CertSvc service if required.

### Proposed properties
[Required, Description("Specifies the URI location where issuer of certificate is located")] String AiaUriPath[];
[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
[Key, Description("Specifies the resource is a single instance, the value must be 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
[Write, Description("Specifies if the service should be restarted.")] Boolean RestartService;

        AdcsAIAExtension AddUriPath
        {
            AiaUriPath       = @(
                'http://setAIAPathTest1/Certs/<CATruncatedName>.cer'
                'http://setAIAPathTest2/Certs/<CATruncatedName>.cer'
                'http://setAIAPathTest3/Certs/<CATruncatedName>.cer'
            )
            Ensure           = 'Present'
            IsSingleInstance = 'Yes'
            Restartservice   = $true
        }

### Special considerations or limitations
N/A

**Comment by mavratar** [comment]
@PlagueHO  Daniel, this is another resource our team would like to contribute.  Thanks.

**Comment by PlagueHO** [comment]
This is now handled by the new AdcsAuthorityInformationAccess resource, so I'll close this. This resource will be released once I've completed #105
