### ISSUE TITLE
AdcsTemplate documentation is missing from the Wiki

### ISSUE THREAD

**Issue by X-Guardian** [dsccommunity/ActiveDirectoryCSDsc#93]
Opportunity to implement the [Publish Wiki Content](https://github.com/PowerShell/DscResource.Tests#publish-wiki-content) task?

**Comment by PlagueHO** [comment]
@X-Guardian - great idea! I'm just working on another PR for this repo now (rushing to get it in before release next week), but feel free to submit a PR.

**Comment by PlagueHO** [comment]
Although I guess we're going to need to set up an encrypted token for publishing to the Wiki.

**Comment by X-Guardian** [comment]
Yes, we need a GitHub Personal Access Token with repo/public_repo permissions for a user that has at least Collaborator access to the PowerShell/ActiveDirectoryCSDsc GitHub repository. Can you get this?

I will create a PR with the other changes needed.

**Comment by PlagueHO** [comment]
Closing this one because it is completed with #111
