### ISSUE TITLE
The Github Releases page is missing the 4.0.0 release from Aug 7th 2019 

### ISSUE THREAD

**Issue by X-Guardian** [dsccommunity/ActiveDirectoryCSDsc#99]

**Comment by PlagueHO** [comment]
It looks like this was a problem in the most recent PSGallery release for all modules. I can see this happened with ComputerManagementDsc and SQLServerDsc.

I suspect that something went wrong in the deployment automation in the most recent release. Tagging @gaelcolas and @mgreenegit as we might need to look into the PSGallery automation prior to the next release.

**Comment by mgreenegit** [comment]
Iirc this one had to be truncated because the Gallery would not accept so much text.  We could manually fix up files in GH?

**Comment by mgreenegit** [comment]
I’m not sure that the automation script handled the GH releases page?  I can take a look.

**Comment by gaelcolas** [comment]
I think what's missing is the git tag. Will look into it tomorrow.
Gael

**Comment by PlagueHO** [comment]
Thanks @mgreenegit & @gaelcolas - possibly a step that was performed manually. Should be something we could automate fairly easily later on.

**Comment by PlagueHO** [comment]
This is fixed now.
